const ADMIN_USER_CONFIG = {
  PAGINATION_LIMIT: 20,
};

const ADMIN_FEED_CONFIG = {
  PAGINATION_LIMIT: 20,
};

export const ADMIN_CONFIG = {
  USERS: ADMIN_USER_CONFIG,
  FEEDS: ADMIN_FEED_CONFIG,
};
